import Head from 'next/head'
import Image from 'next/image'
import useFacebook from '../facebook'
import styles from '../styles/Home.module.css'

export default function Home() {

  const {pixelId, trackEvent} = useFacebook()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Your facebook pixel ID is {pixelId}
          
        </p>

        <div className={styles.grid}>
          <a href="" className={styles.card} 
          onClick={(e) => {
            e.preventDefault()
            trackEvent('ViewContent', {
              content_name: 'Really Fast Running Shoes',
              content_category: 'Apparel & Accessories > Shoes',
              content_ids: ['1234'],
              content_type: 'product',
              value: 0.5,
              currency: 'USD',
            })
            alert('Event trigged')
          }}
          >
            <h2>Facebook sample &rarr;</h2>
            <p>Track View Content Event by clicking here. Use your facebook pixel event test dashboard to verify pixel interaction.</p>
          </a>
      
        </div>              
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
